from .event import eventDeleteView
from .event import eventUpdateView
from .event import eventDetailView
from .event import eventCreateView
from .event import eventListView
from .organization import OrganizationDeleteView
from .organization import OrganizationUpdateView
from .organization import OrganizationDetailView
from .organization import OrganizationCreateView
from .organization import OrganizationListView
